# Generated by Django 2.2 on 2019-04-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_auto_20190414_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='facebook',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='github',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='linkedin',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='twitter',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
