# Generated by Django 2.2 on 2019-04-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0003_auto_20190415_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
