# Generated by Django 2.2 on 2019-04-15 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_education_developer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='instution_name',
            new_name='institution_name',
        ),
    ]
